<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:output encoding="UTF-8" indent="no" media-type="text/html" method="html">
<!-- generated by dexter-0.3.0-beta (copyright (c) 2007-2009 Michael Dykman) from `workspace/gossamer/content/xsl/default/xhtml-1.0/scon/list.html.xsl'  -->
</xsl:output>
<xsl:template match="/">
		<xsl:element name="xsl:stylesheet"><xsl:attribute name="version">1.0</xsl:attribute><xsl:attribute name="xmlns:xsl">http://www.w3.org/1999/XSL/Transform</xsl:attribute>			<xsl:element name="xsl:output"><xsl:attribute name="doctype-public">-//W3C//DTD XHTML 1.0 Strict//EN</xsl:attribute><xsl:attribute name="doctype-system">http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd</xsl:attribute><xsl:attribute name="encoding">UTF-8</xsl:attribute><xsl:attribute name="indent">no</xsl:attribute><xsl:attribute name="media-type">text/html</xsl:attribute><xsl:attribute name="method">html</xsl:attribute>				<xsl:text>
</xsl:text>
							<!-- generated by dexter from `../content/xsl/default/xhtml-1.0/scon/list.html'  -->
							<xsl:text>
</xsl:text>
			</xsl:element>

					<xsl:element name="xsl:template"><xsl:attribute name="match">/</xsl:attribute>				<xsl:element name="xsl:element"><xsl:attribute name="name">html</xsl:attribute>					<xsl:text>
</xsl:text>
									<xsl:element name="xsl:element"><xsl:attribute name="name">head</xsl:attribute>						<xsl:text>
</xsl:text>
					</xsl:element>

									<xsl:text>
</xsl:text>
									<xsl:element name="xsl:element"><xsl:attribute name="name">body</xsl:attribute>						<xsl:text>
</xsl:text>
											<xsl:element name="xsl:element"><xsl:attribute name="name">script</xsl:attribute>							<xsl:element name="xsl:attribute"><xsl:attribute name="name">type</xsl:attribute>								<xsl:text>text/javascript</xsl:text>
							</xsl:element>

													<xsl:text>
</xsl:text>
						</xsl:element>

											<xsl:text>
</xsl:text>
											<xsl:element name="xsl:element"><xsl:attribute name="name">div</xsl:attribute>							<xsl:text>
</xsl:text>
													<xsl:element name="xsl:element"><xsl:attribute name="name">span</xsl:attribute>								<xsl:element name="xsl:attribute"><xsl:attribute name="name">style</xsl:attribute>									<xsl:text>font-style: italic;</xsl:text>
								</xsl:element>

															<xsl:element name="xsl:value-of"><xsl:attribute name="select">result/type</xsl:attribute></xsl:element>

							</xsl:element>

													<xsl:text> files
</xsl:text>
						</xsl:element>

											<xsl:text>

</xsl:text>
											<xsl:element name="xsl:for-each"><xsl:attribute name="select">result/files/item</xsl:attribute>							<xsl:element name="xsl:element"><xsl:attribute name="name">div</xsl:attribute>								<xsl:text>
[</xsl:text>
															<xsl:element name="xsl:element"><xsl:attribute name="name">a</xsl:attribute>									<xsl:element name="xsl:attribute"><xsl:attribute name="name">onclick</xsl:attribute>										<xsl:element name="xsl:choose">											<xsl:element name="xsl:when"><xsl:attribute name="test">./text()</xsl:attribute>												<xsl:element name="xsl:text">													<xsl:text>deleteScript('</xsl:text>
												</xsl:element>

																							<xsl:element name="xsl:value-of"><xsl:attribute name="select">.</xsl:attribute></xsl:element>

																							<xsl:element name="xsl:text">													<xsl:text>');</xsl:text>
												</xsl:element>

											</xsl:element>

																					<xsl:element name="xsl:otherwise">												<xsl:element name="xsl:text"/>

											</xsl:element>

										</xsl:element>

									</xsl:element>

																	<xsl:element name="xsl:attribute"><xsl:attribute name="name">href</xsl:attribute>										<xsl:text>javascript:void(0);</xsl:text>
									</xsl:element>

																	<xsl:text>x</xsl:text>
								</xsl:element>

															<xsl:text>]
</xsl:text>
															<xsl:element name="xsl:element"><xsl:attribute name="name">a</xsl:attribute>									<xsl:element name="xsl:attribute"><xsl:attribute name="name">onclick</xsl:attribute>										<xsl:element name="xsl:choose">											<xsl:element name="xsl:when"><xsl:attribute name="test">./text()</xsl:attribute>												<xsl:element name="xsl:text">													<xsl:text>loadScript('</xsl:text>
												</xsl:element>

																							<xsl:element name="xsl:value-of"><xsl:attribute name="select">.</xsl:attribute></xsl:element>

																							<xsl:element name="xsl:text">													<xsl:text>');</xsl:text>
												</xsl:element>

											</xsl:element>

																					<xsl:element name="xsl:otherwise">												<xsl:element name="xsl:text"/>

											</xsl:element>

										</xsl:element>

									</xsl:element>

																	<xsl:element name="xsl:attribute"><xsl:attribute name="name">href</xsl:attribute>										<xsl:text>javascript:void(0);</xsl:text>
									</xsl:element>

																	<xsl:element name="xsl:value-of"><xsl:attribute name="select">.</xsl:attribute></xsl:element>

								</xsl:element>

															<xsl:text>
</xsl:text>
							</xsl:element>

						</xsl:element>

											<xsl:text>


</xsl:text>
					</xsl:element>

									<xsl:text>
</xsl:text>
				</xsl:element>

			</xsl:element>

		</xsl:element>

	</xsl:template>
</xsl:stylesheet>